FROM python:3.14-slim
WORKDIR /app
ENV PIP_NO_CACHE_DIR=1 PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1

RUN groupadd -r appuser && useradd -r -g appuser appuser

RUN pip install --no-cache-dir --upgrade pip setuptools

RUN pip install --no-cache-dir --index-url https://download.pytorch.org/whl/cpu torch==2.13.0+cpu

COPY requirements.base.txt requirements.worker.txt ./
RUN pip install --no-cache-dir -r requirements.worker.txt

COPY ./app ./app
COPY ./worker ./app/worker

RUN chown -R appuser:appuser /app
ENV HF_HOME=/app/.cache/huggingface
USER appuser
CMD ["celery", "-A", "app.worker.celery_app", "worker", "-Q", "infer,ingress", "--concurrency=4"]